export enum GameStatus {
    WAITING_FOR_OPPONENT = 'WAITING_FOR_OPPONENT',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    WHITE_WINS = 'WHITE_WINS',
    BLACK_WINS = 'BLACK_WINS',
    DRAW = 'DRAW',
    ABORTED = 'ABORTED',
}