export enum ReasonForEnding {
    CHECKMATED = 'CHECKMATE',
    RESIGNED = 'RESIGNED',
    STALEMATE = 'STALEMATE',
    DRAW_AGREEMENT = 'DRAW_AGREEMENT',
    REPETITION = 'REPETITION',
    INSUFFICIENT_MATERIAL = 'INSUFFICIENT_MATERIAL',
    DISCONNECT = 'DISCONNECT',
    TIMEOUT = 'TIMEOUT',
    ABORTED = 'ABORTED'
}